#!/bin/bash
# */5 * * * * $HOME/nut/cron
DIR=$(dirname "$0")
(
		flock -n 9 || exit 1
		$DIR/nut.py -UV > /dev/null 2>&1
		$DIR/nut.py > /dev/null 2>&1
		$DIR/nut.py -so --unlock-all > /dev/null 2>&1
		$DIR/nut.py --scrape-delta
) 9>$DIR/.lock