#!/bin/bash
# */5 * * * * flock -n /var/lock/nut.lock $HOME/nut/cron
DIR=$(dirname "$0")
$DIR/nut.py -UV > /dev/null 2>&1
$DIR/nut.py > /dev/null 2>&1
$DIR/nut.py -so --unlock-all > /dev/null 2>&1
$DIR/nut.py --scrape-delta
